### ISSUE TITLE
job_do_segmentCAT12 with `par.sge=1` does not work correcly with `extopts.expertgui=2`

### ISSUE THREAD

**Issue by benoitberanger** [romainVala/matvol#111]
https://github.com/romainVala/matvol/blob/597405ae2183c02e02e50eafa222608b80e076a2/SPM/preproc/job_do_segmentCAT12.m#L143

At the moment, with an unedited `cat_defaults.m` file, this *cmd_prepend* line is not enough to activate the *expertgui* option in the case if cluster execution.

**Comment by romainVala** [comment]
ok je pense que le plus simple c'est de rajoute directement dans le scrip matvol
job_do_segmentCAT12
au lieu de faire le assert (ligne 152) on fait 
global cat; cat_defaults; cat.extopts.subfolders=par.subfolder;
cat.extopts.expertgui = 2

**Comment by benoitberanger** [comment]
j'ai déjà testé, ça marche pas -> l'initialisation de SPM (et de CAT12) doit être fait APRES `expertgui = 2`
recheck de ton côté tu me diras
j'ai pas trouvé de solution qui marche bien, c'est pour cela que j'ai demandé de l'aide...

**Comment by benoitberanger** [comment]
bonne remarque ! à vérifier si avec une version plus récente ça passe 
dans les logs de CAT12, il ya le numéro de version dans les 1ières lignes

**Comment by romainVala** [comment]
cat12.m 1275 2018-02-12

**Comment by benoitberanger** [comment]
le fix : 
`spm_jobman('initcfg'); global cat; cat_defaults; cat.extopts.subfolders=0;`

**Comment by benoitberanger** [comment]
probably better : 
`spm_jobman('initcfg'); global cat; cat_defaults; cat.extopts.expertgui=2; cat.extopts.subfolders=0;`

**Comment by benoitberanger** [comment]
24b8cc9
