### ISSUE TITLE
Example of par input

### ISSUE THREAD

**Issue by mjansen983** [romainVala/matvol#36]
Hi,

I am new to Github and relatively new to Matlab and was wondering whether you could give an example of how to use par as input for this function. Do you need to construct the variable beforehand? What if you would like to use the default?

**Comment by romainVala** [comment]
Hi 
this is an ongoing code, so nothing very professional but I tried to make all fonction similar
il you do not specify the par, it will take the default value
and to specify it just define a struct
mypar.prefix = 'test'
and use the variable mypar as last argument
