### ISSUE TITLE
error pops when mak contains NaN

### ISSUE THREAD

**Issue by askrzatek** [romainVala/matvol#91]
https://github.com/romainVala/matvol/blob/62f16def2cbe3ae48a42534e442bde7df52664bc/SPM/firstlevel/job_extract_timeseries.m#L602

solution : isfinite
`logical(mask_global_Y(isfinite(mask_global_Y)));`

**Comment by askrzatek** [comment]
mask_global_Y(~isfinite(mask_global_Y)) = 0

**Comment by benoitberanger** [comment]
solved by #98
