### ISSUE TITLE
input roi order is not conserved

### ISSUE THREAD

**Issue by LisObk** [romainVala/matvol#97]
https://github.com/romainVala/matvol/blob/62f16def2cbe3ae48a42534e442bde7df52664bc/SPM/firstlevel/job_timeseries_to_connectivity_matrix.m#L117

solution : 
[~,~,idx_roi_in_netwok] = intersect(n.roi, ts_data.ts_table.abbreviation, 'stable')

**Comment by benoitberanger** [comment]
solved by #98
